### ISSUE TITLE
AdGuard psuje witryny zamiast blokować

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#905]
Właśnie testuje sobie AdGuarda i filtr KAD w AdGuarda nie blokuje strony tylko ją rozwala.
Tutaj przykład:

![Screenshot_20190526_005235](https://user-images.githubusercontent.com/36385327/58375340-9b3ba780-7f50-11e9-85c7-cdbf59e4321a.png) |
--- |

A tutaj przykład z innym filtrem:

![Screenshot_20190526_004838](https://user-images.githubusercontent.com/36385327/58375342-abec1d80-7f50-11e9-8868-8d1bc255e24d.png) |
--- |

Uważam, że powinno to zostać poprawione gdyż ktoś po prostu będzie myślał, że to jest jakiś błąd i wyłączy AdGuarda.

**Comment by hawkeye116477** [comment]
Raczej wątpię, że my to naprawimy. AdGuard najwyraźniej nie ma bezpośredniego blokowania stron, tak jak ABP. No chyba, że kiedyś to działało i potem to popsuli. @AdamWr @F4z Jak to jest?

**Comment by xMaap** [comment]
AdGuarda blokuje stronę z filtru "Malware domains"
![Screenshot_20190526_101917](https://user-images.githubusercontent.com/36385327/58379120-cb5e6700-7f9f-11e9-8500-c7e386e4c8da.png)
Blokuje stronę z filtru "Spam404"
![Screenshot_20190526_102005](https://user-images.githubusercontent.com/36385327/58379131-efba4380-7f9f-11e9-85fe-e10773c20458.png)
A tutaj z "KAD" po prostu rozwala stronę
![Screenshot_20190526_102504](https://user-images.githubusercontent.com/36385327/58379173-97377600-7fa0-11e9-9845-84bc22740074.png)

**Comment by hawkeye116477** [comment]
@xMaap Rozszerzenie do przeglądarki na pewno nie blokuje dostępu, bo to nawet sprawdziłem, a reguły są te same. Tak więc my tu nic nie poprawimy, to musi AdGuard poprawić :smile:

**Comment by hawkeye116477** [comment]
@xMaap Blokowanie tego działa tylko po włączeniu opcji Ochrona przed phishingiem i malware, te listy filtrów nie mają z tym nic wspólnego.

**Comment by krystian3w** [comment]
Suplement dla AdGuard z wycinaniem `<BODY>` na stronach a w zaawansowanych coś w stylu:

```css
html::before
  {
    content: "Ta strona została zablokowana po przez filtry KAD.\aKorzystanie z niej może być niebezpieczne";
    white-space: pre;
    position: fixed;
    top: 20px;
    left: 20px;
    z-index: 200000;
    padding: 15px;
    background: yellow;
    border: yellowgreen 5px solid;
    border-radius: 15px;
  }
}
```

---

Ja tam mam największe ubolewanie że skrócony zapis nie blokuje skryptów liniowych.
